on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing github action'
        run: pwd

      - name: 'display files before add action function'
        run: ls

      -uses: action/checkout@v3 

      - name: 'display files after add action function'
        run: ls 




